"""your message

Revision ID: 035f3fd9f3f6
Revises: be5b0549e251
Create Date: 2025-03-05 14:31:37.557293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035f3fd9f3f6'
down_revision = 'be5b0549e251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_phone_key', 'client', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('client_phone_key', 'client', ['phone'])
    # ### end Alembic commands ###
